version: "3.8"

services:
  app:
    build: .
#    image: platziapp
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3001:3000"
    volumes:
      - .:/usr/src
      #Ignore this path to mount
      - /usr/src/node_modules
    #Adjust command run when start container
    command: npx nodemon --legacy-watch index.js

  db:
    image: mongo
